### ISSUE TITLE
Gravatars loaded from https sources instead of http?

### ISSUE THREAD

**Issue by SirLouen** [realdigger/SMF-Gravatar#1]
It is possible to edit loading of gravatars from https sources instead of http?
Example:
Now is loading from:
http://gravatar.com/avatar/cf919c36e061b528c02ff58ba9e6d221?d=identicon&s=65&r=g

But could be loaded from:
https://gravatar.com/avatar/cf919c36e061b528c02ff58ba9e6d221?d=identicon&s=65&r=g

This way, it is better for https based forums.

**Comment by realdigger** [comment]
This is a SMF issue. 
http://www.simplemachines.org/community/index.php?topic=547599.0
http://www.simplemachines.org/community/index.php?topic=541642.0

**Comment by realdigger** [comment]
Fixed in SMF 2.0.14
